package com.thebridge.app.ui.sanctuary

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.thebridge.app.R

// Shared palette — matches AvatarWalkthrough.kt. If these get promoted to a
// single shared theme file later, update both call sites together.
private val Charcoal = Color(0xFF0A0500)
private val Gold = Color(0xFFD4AF37)
private val Parchment = Color(0xFFF5E8C7)

/**
 * The six pieces of the Armor of God, Ephesians 6:14-17, in verse order.
 *
 * Verse text is NIV (2011, Biblica/Zondervan) — verbatim per piece, do not
 * paraphrase or edit wording. NIV is copyrighted; Ricky made this call
 * explicitly, aware of the licensing considerations (Biblica's general-use
 * quotation allowance covers volume here, but Biblica's stated policy also
 * requires a license for use "in connection with" AI/ML features, which
 * this app has elsewhere — Ricky accepted that risk knowingly, this is not
 * a resolved/cleared legal question). Per Biblica's own attribution
 * requirement, "NIV" must appear at the end of each quotation — see
 * `verseReference` below, and the required copyright notice must appear
 * somewhere in the app (Settings/credits screen — not built yet, flagging
 * for whenever that screen gets built):
 *
 *   Scripture quotations taken from The Holy Bible, New International
 *   Version®, NIV®. Copyright © 1973, 1978, 1984, 2011 by Biblica, Inc.
 *   Used by permission. All rights reserved worldwide.
 *
 * Art: all six pieces now render real watercolor illustrations (Google Flow,
 * generated by Ricky 2026-09-05/06) — see ASSETS.md for provenance and the
 * open licensing question. Every source image is 16:9, which is why
 * [ArmorArt] below draws at 16:9 rather than the square block the old
 * placeholder used.
 *
 * NOT uniform quality yet: belt, shield, helmet and sword are true
 * illustrations at 1376x768. Breastplate and shoes are saved *video frames*
 * at 640x360 and will look visibly soft next to the other four, since they
 * upscale roughly 1.5-2x at render width. They are wired in deliberately as
 * an improvement over a bordered placeholder box, not as final art. Swapping
 * them is a drop-in file replacement at the same resource names — no code
 * change needed.
 */
enum class ArmorPiece(
    val displayName: String,
    val verseReference: String,
    val verseText: String,
    val affirmation: String,
    val artResId: Int,
) {
    BELT_OF_TRUTH(
        displayName = "Belt of Truth",
        verseReference = "Ephesians 6:14 (NIV)",
        verseText = "Stand firm then, with the belt of truth buckled around your waist",
        affirmation = "I stand in what is true.",
        artResId = R.drawable.armor_belt_of_truth,
    ),
    BREASTPLATE_OF_RIGHTEOUSNESS(
        displayName = "Breastplate of Righteousness",
        verseReference = "Ephesians 6:14 (NIV)",
        verseText = "with the breastplate of righteousness in place",
        affirmation = "My heart is guarded and made right.",
        artResId = R.drawable.armor_breastplate_of_righteousness,
    ),
    SHOES_OF_THE_GOSPEL_OF_PEACE(
        displayName = "Shoes of the Gospel of Peace",
        verseReference = "Ephesians 6:15 (NIV)",
        verseText = "and with your feet fitted with the readiness that comes from the gospel of peace",
        affirmation = "I walk ready, at peace.",
        artResId = R.drawable.armor_shoes_of_the_gospel_of_peace,
    ),
    SHIELD_OF_FAITH(
        displayName = "Shield of Faith",
        verseReference = "Ephesians 6:16 (NIV)",
        verseText = "In addition to all this, take up the shield of faith, with which you " +
            "can extinguish all the flaming arrows of the evil one",
        affirmation = "I trust what I cannot see.",
        artResId = R.drawable.armor_shield_of_faith,
    ),
    HELMET_OF_SALVATION(
        displayName = "Helmet of Salvation",
        verseReference = "Ephesians 6:17 (NIV)",
        verseText = "Take the helmet of salvation",
        affirmation = "My mind is protected.",
        artResId = R.drawable.armor_helmet_of_salvation,
    ),
    SWORD_OF_THE_SPIRIT(
        displayName = "Sword of the Spirit",
        verseReference = "Ephesians 6:17 (NIV)",
        verseText = "and the sword of the Spirit, which is the word of God",
        affirmation = "God's word is my strength.",
        artResId = R.drawable.armor_sword_of_the_spirit,
    ),
}

/**
 * Sanctuary — the Armor of God ceremony. One screen, six sequential internal
 * steps. Each step: the piece's illustration + verbatim verse + affirmation, then a
 * tap-to-confirm advance (no auto-advance, matching the app's existing
 * pattern everywhere else — post-John path selection, WordForge delivery).
 *
 * On confirming the sixth piece, the fully-armored closing state shows once,
 * then [onCeremonyComplete] fires exactly once. The caller (see wiring notes
 * below) is responsible for logging the ledger event — this composable holds
 * no database dependency itself, same separation OnboardingRouter uses to
 * stay unit-testable without instrumentation.
 *
 * HARD RULE — do not violate this in any future edit: no streak counter, no
 * completion count, no visible progress indicator, no badge. The signal this
 * ceremony produces is backend-only instrumentation data. Nothing about "how
 * many times you've done this" is ever surfaced to the user, anywhere.
 */
@Composable
fun Sanctuary(onCeremonyComplete: () -> Unit) {
    var stepIndex by remember { mutableIntStateOf(0) }
    val pieces = ArmorPiece.entries
    val isClosingState = stepIndex >= pieces.size

    Surface(modifier = Modifier.fillMaxSize(), color = Charcoal) {
        if (!isClosingState) {
            ArmorStep(
                piece = pieces[stepIndex],
                onConfirm = { stepIndex += 1 },
            )
        } else {
            ArmoredClosing(onContinue = onCeremonyComplete)
        }
    }
}

@Composable
private fun ArmorStep(piece: ArmorPiece, onConfirm: () -> Unit) {
    Column(
        modifier = Modifier.fillMaxSize().padding(24.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center,
    ) {
        ArmorArt(piece = piece)

        Spacer(modifier = Modifier.height(28.dp))

        Text(
            text = piece.displayName,
            color = Gold,
            fontSize = 22.sp,
            fontWeight = FontWeight.Bold,
            textAlign = TextAlign.Center,
        )

        Spacer(modifier = Modifier.height(16.dp))

        Text(
            text = "\u201c${piece.verseText}\u201d",
            color = Parchment,
            fontSize = 17.sp,
            fontStyle = FontStyle.Italic,
            textAlign = TextAlign.Center,
            lineHeight = 24.sp,
        )

        Spacer(modifier = Modifier.height(8.dp))

        Text(
            text = piece.verseReference,
            color = Parchment.copy(alpha = 0.6f),
            fontSize = 13.sp,
            textAlign = TextAlign.Center,
        )

        Spacer(modifier = Modifier.height(24.dp))

        Text(
            text = piece.affirmation,
            color = Gold,
            fontSize = 18.sp,
            fontWeight = FontWeight.Bold,
            textAlign = TextAlign.Center,
        )

        Spacer(modifier = Modifier.height(40.dp))

        Button(
            onClick = onConfirm,
            colors = ButtonDefaults.buttonColors(containerColor = Gold, contentColor = Charcoal),
            modifier = Modifier.fillMaxWidth(),
        ) {
            Text(text = "Put it on", fontWeight = FontWeight.Bold)
        }
    }
}

/**
 * The piece's illustration, framed as a plate: the source art sits on cream
 * parchment, so a gold border on the charcoal ground reads as an illuminated
 * page rather than a bright rectangle floating loose.
 *
 * 16:9 matches every source image exactly, so nothing is cropped. If a
 * replacement asset is ever authored at a different ratio, change it here —
 * do not letterbox it into this one.
 */
@Composable
private fun ArmorArt(piece: ArmorPiece) {
    Image(
        painter = painterResource(id = piece.artResId),
        contentDescription = piece.displayName,
        contentScale = ContentScale.Fit,
        modifier = Modifier
            .fillMaxWidth()
            .aspectRatio(16f / 9f)
            .clip(RoundedCornerShape(16.dp))
            .border(width = 2.dp, color = Gold.copy(alpha = 0.5f), shape = RoundedCornerShape(16.dp)),
    )
}

@Composable
private fun ArmoredClosing(onContinue: () -> Unit) {
    Column(
        modifier = Modifier.fillMaxSize().padding(24.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center,
    ) {
        // Closing placeholder — the ONLY armor art still missing. The six
        // individual pieces are now real illustrations; this is the seventh
        // asset: either those six composited onto one base figure, or a
        // single illustration showing all pieces worn together. Not sourced
        // yet. Sized 16:9 to match the six real plates, so dropping the
        // asset in is a swap to Image() with no layout change.
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .aspectRatio(16f / 9f)
                .background(Charcoal)
                .border(width = 2.dp, color = Gold, shape = RoundedCornerShape(16.dp)),
            contentAlignment = Alignment.Center,
        ) {
            Text(
                text = "(fully armored — placeholder)",
                color = Gold.copy(alpha = 0.7f),
                fontSize = 14.sp,
                fontStyle = FontStyle.Italic,
                textAlign = TextAlign.Center,
            )
        }

        Spacer(modifier = Modifier.height(32.dp))

        Text(
            text = "Fully armored.",
            color = Gold,
            fontSize = 24.sp,
            fontWeight = FontWeight.Bold,
        )

        Spacer(modifier = Modifier.height(40.dp))

        Button(
            onClick = onContinue,
            colors = ButtonDefaults.buttonColors(containerColor = Gold, contentColor = Charcoal),
            modifier = Modifier.fillMaxWidth(),
        ) {
            Text(text = "Continue", fontWeight = FontWeight.Bold)
        }
    }
}
